{% set version = "2.7.0" %}

package:
  name: livereload
  version: {{ version }}

source:
  url: https://github.com/lepture/python-livereload/archive/{{ version }}.tar.gz
  sha256: ecb6fb93d89ff9d8924630e565c707c7af7b6c23b72a0e189168bcab4abed4fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - livereload = livereload.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - tornado
    - six

test:
  imports:
    - livereload
  commands:
    - pip check
    - livereload --help
  requires:
    - pip

about:
  home: https://github.com/lepture/python-livereload
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python LiveReload is an awesome tool for web developers

extra:
  recipe-maintainers:
    - ocefpaf
